// GENERATED by scripts/optimize-gallery.ts — run `npm run gallery` to refresh.
// Pixel size of each file in /public/gallery, for intrinsic size and aspect ratio.

export interface PosterSize {
  width: number
  height: number
}

export const posterSizes: Record<string, PosterSize> = {
  'akiassc-2026': { width: 720, height: 900 },
  'error-404-debugging': { width: 720, height: 720 },
  'connect-the-lives': { width: 720, height: 900 },
  'morse-code-contest': { width: 720, height: 720 },
  'ai-robotics-space-sustainability': { width: 720, height: 960 },
  'women-in-tech-beyond-stereotypes': { width: 720, height: 720 },
  'environment-day': { width: 720, height: 1082 },
  'pes-day-2026': { width: 720, height: 720 },
  'sps-world-of-opportunities': { width: 720, height: 900 },
  'a-robo-roadmap': { width: 720, height: 721 },
  'women-leading-innovation': { width: 720, height: 900 },
  'linkedin-industry-success': { width: 720, height: 720 },
  'power-electronics-talk': { width: 720, height: 901 },
  'farewell-2026': { width: 720, height: 720 },
  'informatyka-agentic-ai': { width: 720, height: 900 },
  'understanding-gender-reality': { width: 720, height: 720 },
  'distinguished-lecture-deep-learning': { width: 720, height: 900 },
  'sps-scholarship-guidance': { width: 720, height: 720 },
  'ethical-ai-session-1': { width: 720, height: 900 },
  'the-power-quest': { width: 720, height: 720 },
  'linkedin-industry-success-rescheduled': { width: 720, height: 720 },
  'ev-career-pathways': { width: 720, height: 720 },
}
