/**
 * Rebuilds the optimized event-poster set: `npm run gallery`
 *
 * Reads every poster listed in src/content.ts and writes exactly one WebP each,
 * POSTER_WIDTH wide (never upscaling past the source), plus a manifest of the
 * rendered pixel sizes so the renderer can set intrinsic size and aspect ratio.
 *
 * One file per poster, one format, one width — no responsive tiers and no
 * fallback formats. WebP is understood by every browser since ~2020.
 *
 * Requires ImageMagick 7 (`magick`) on PATH.
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { POSTER_WIDTH, galleryPosters } from '../src/lib/content.ts'
import type { GalleryPoster } from '../src/lib/content.ts'

const root = resolve(fileURLToPath(import.meta.url), '../..')
const sourceDir = join(root, 'images')
const outDir = join(root, 'public', 'gallery')
const manifestPath = join(root, 'src', 'lib', 'gallery-manifest.generated.ts')

/** WebP quality — 80 is the usual sweet spot for photographic posters. */
const WEBP_QUALITY = 80

interface Size {
  width: number
  height: number
}

function run(cmd: string, args: string[]): string {
  return execFileSync(cmd, args, { encoding: 'utf8' }).trim()
}

function dimensions(file: string): Size {
  const [w, h] = run('magick', ['identify', '-format', '%w %h', file]).split(' ')
  return { width: Number(w), height: Number(h) }
}

function kb(file: string): number {
  return Math.round(statSync(file).size / 1024)
}

function optimize(poster: GalleryPoster): Size {
  const source = join(sourceDir, poster.source)
  const out = join(outDir, `${poster.slug}.webp`)
  const sourceBytes = statSync(source).size

  // `720x>` shrinks to 720 wide but leaves anything already narrower alone.
  run('magick', [
    source,
    '-auto-orient',
    '-colorspace',
    'sRGB',
    '-filter',
    'Lanczos',
    '-resize',
    `${POSTER_WIDTH}x>`,
    '-strip',
    '-quality',
    String(WEBP_QUALITY),
    '-define',
    'webp:method=6',
    '-define',
    'webp:sharp-yuv=true',
    out,
  ])

  const rendered = dimensions(out)
  console.log(
    `  ${poster.slug.padEnd(38)} ${Math.round(sourceBytes / 1024)}KB source` +
      ` · ${rendered.width}x${rendered.height}` +
      ` · ${kb(out)}KB webp`,
  )
  return rendered
}

function writeManifest(entries: Map<string, Size>): void {
  const body = [...entries]
    .map(([slug, size]) => `  '${slug}': { width: ${size.width}, height: ${size.height} },`)
    .join('\n')

  writeFileSync(
    manifestPath,
    `// GENERATED by scripts/optimize-gallery.ts — run \`npm run gallery\` to refresh.\n` +
      `// Pixel size of each file in /public/gallery, for intrinsic size and aspect ratio.\n\n` +
      `export interface PosterSize {\n  width: number\n  height: number\n}\n\n` +
      `export const posterSizes: Record<string, PosterSize> = {\n${body}\n}\n`,
    'utf8',
  )
}

function main(): void {
  try {
    run('magick', ['-version'])
  } catch {
    throw new Error('Missing required tool: magick (ImageMagick 7). Install it and re-run.')
  }

  rmSync(outDir, { recursive: true, force: true })
  mkdirSync(outDir, { recursive: true })

  console.log(`Optimizing ${galleryPosters.length} posters → public/gallery`)
  const entries = new Map<string, Size>()
  for (const poster of galleryPosters) {
    if (entries.has(poster.slug)) throw new Error(`Duplicate gallery slug: ${poster.slug}`)
    entries.set(poster.slug, optimize(poster))
  }

  writeManifest(entries)
  console.log(`Wrote ${entries.size} entries to src/lib/gallery-manifest.generated.ts`)
}

main()
